# Problem 2 - Even Fibonacci numbers
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
#
# Answer: 4613732

def problem2():
    x, y, sum = 1, 2, 2
    while x+y < 4000000: # 4000000 can be a parameter
        temp = x+y
        x, y = y, temp
        if temp % 2 == 0:
            sum = sum + temp
    print("Sum is: ", sum)
    
problem2()
